workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: https://api.unkey.dev/openapi.json
        registry:
            location: registry.speakeasyapi.dev/sagar-demo/sagar-demo/openapi
targets:
    unkey-go:
        target: go
        source: openapi
        output: ./sdk/go
